;[target]
;sDefaultHost =                ; Defines the default hostname/IP, unless a hostname/IP was specified on the commandline.
;sDefaultPort =                ; Defines the default port, unless a port was specified on the commandline.
;sDefaultPass =                ; Defines the default password, unless a password was specified on the commandline.
;bAllowNoArgs = false          ; When true, the default action with no arguments is to connect to the above target.

[appearance]
bDisablePrompt = false        ; When true, this is the equivalent of always specifying the --no-prompt option.
;bDisableColors = false        ; When true, this is the equivalent of always specifying the -n/--no-color option.
;sCustomPrompt =               ; Accepts a string to use in place of the default prompt, excluding the end, which is always "> ".
;bEnableBukkitColors = false   ; Enables support for Bukkit's color syntax. This is only relevant for minecraft servers running Bukkit.

;[timing]
;iCommandDelay = 0             ; The delay in milliseconds between sending each command when using commandline/scriptfile mode.
;iReceiveDelay = 10            ; The time in milliseconds to wait after receiving packets. Raise this if multi-packet responses aren't fully received. 
;iSelectTimeout = 500          ; The max amount of time to wait for packets before timing out. Raise this if your network is slow.